# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      upload-coverage: true

  tag-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Run latest-tag
      uses: EndBug/latest-tag@v1.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==6.0.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: semantic-release
      uses: python-semantic-release/python-semantic-release@v8.1.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
