# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      upload-coverage: true

  tag-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Run latest-tag
      uses: EndBug/latest-tag@v1.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  semantic-release:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: pip
    - name: Install dependencies
      # download upx from https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-win64.zip
      run: |
        python -m pip install --upgrade pip
        pip install python-semantic-release==8.1.1 pyinstaller==6.0.0 pyqt5-tools==5.15.9.3.3
        pip install -r requirements.txt
    - name: semantic-release
      # there's a step in the build process that involves downloading a docker image
      run: |
        python -m semantic_release version
