name: GitHub Cache Housekeeping Script

on:
  workflow_dispatch:

jobs:
  gh_cache_housekeeping_script:
    runs-on: ubuntu-latest
    steps:
    - name: Set up environment variables
      run: |
        echo "JOB_START_TS=$(date +%s)" >> $GITHUB_ENV
        echo "DB_PATH=/tmp/ah_db" >> $GITHUB_ENV
    - name: Get AH Database File from GitHub Cache
      uses: actions/cache@v3
      with:
        path: ${{ env.DB_PATH }}
        key: ${{ runner.os }}-ah-${{ env.JOB_START_TS }}
        restore-keys: |
          ${{ runner.os }}-ah-
    # checkout current branch
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Housekeeping Script
      run: >
        PYTHONPATH=. python bin/cache_housekeeping.py
        --db_path ${{ env.DB_PATH }}